DOMAIN = "delayed_action"
ATTR_ENTITY_ID = "entity_id"
ATTR_DELAY = "delay"
ATTR_ACTION = "action"
ATTR_DATETIME = "datetime"
ATTR_ADDITIONAL_DATA = "data"
ATTR_TASK_ID = "task_id"
CONF_DOMAINS = "domains"
ATTR_DOMAINS = ["automation", "climate", "cover", "fan", "humidifier", "input_boolean", "input_select", "lawn_mower", "light", "lock", "media_player", "scene", "script", "select", "switch", "vacuum", "water_heater"]